In [1]:
import numpy as np

# Reverse a numpy array
https://www.hackerrank.com/challenges/np-arrays/problem?isFullScreen=true

In [2]:
arr = input().strip().split(' ')

1 2 3 4 -8 -10


In [3]:
print(arr)

['1', '2', '3', '4', '-8', '-10']


In [4]:
type(arr)

list

In [5]:
arr.reverse()

In [10]:
print(np.array(arr,float))

[-5.  4.  3.  2.  1.]


In [11]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    return numpy.array(arr,float)
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Shape and Reshape*
https://www.hackerrank.com/challenges/np-shape-reshape/problem?isFullScreen=true

In [12]:
import numpy

arr = input().strip().split(' ')
np_arr = numpy.array(arr,int)
print(numpy.reshape(np_arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten**
https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem?isFullScreen=true

In [ ]:
import numpy

N,M = map(int,input().split(' '))
arr = []
for i in range(N):
    ip_array = input().strip().split(' ')
    arr.append(ip_array)
    
np_arr = numpy.array(arr,int)
print(np_arr.transpose())
print(np_arr.flatten())    

# Concatenate***
https://www.hackerrank.com/challenges/np-concatenate/problem?isFullScreen=true

In [ ]:
import numpy

N,M,P = map(int,input().strip().split(' '))
arr1 = []
for i in range(N):
    ip_array_N = input().strip().split(' ')
    arr1.append(ip_array_N)
    num_arr_n = numpy.array(arr1,int)

arr2=[]
for i in range(M):
    ip_array_M = input().strip().split(' ')
    arr2.append(ip_array_M)
    num_arr_m = numpy.array(arr2,int)


print(numpy.concatenate((num_arr_n,num_arr_m),axis=0))

# Zeros and Ones

https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?isFullScreen=true

In [29]:
import numpy

input_tuple = tuple(map(int,input().strip().split(' ')))
print(numpy.zeros(input_tuple,int))
print(numpy.ones(input_tuple,int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Identity and eye

https://www.hackerrank.com/challenges/np-eye-and-identity/problem?isFullScreen=true

In [34]:
import numpy

numpy.set_printoptions(legacy = '1.13')
m,n = map(int,input().strip().split(' '))
print(numpy.eye(m,n,k=0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array mathematics

https://www.hackerrank.com/challenges/np-array-mathematics/problem?isFullScreen=true

In [39]:
import numpy

n,m = map(int,input().strip().split(' '))
arr_1 = []
arr_2 = []
for i in range(n):
    ip_arr_1 = input().strip().split(' ')
    arr_1.append(ip_arr_1)
    A = numpy.array(arr_1,int)

for i in range(n):
    ip_arr_2 = input().strip().split(' ')
    arr_2.append(ip_arr_2)
    B = numpy.array(arr_2,int)
    
    
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Floor, Ceil and Rint

https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem?isFullScreen=true

In [ ]:
import numpy

numpy.set_printoptions(legacy = '1.13')

List = list(input().strip().split())

num_arr = numpy.array(List,float)

print(numpy.floor(num_arr))
print(numpy.ceil(num_arr))
print(numpy.rint(num_arr))

# Sum and Prod

https://www.hackerrank.com/challenges/np-sum-and-prod/problem?isFullScreen=true

In [ ]:
import numpy

n,m=map(int,input().strip().split())

arr = []
for i in range(n):
    ip_arr = input().strip().split()
    arr.append(ip_arr)

num_arr = numpy.array(arr,int)
sum_num_arr  = numpy.sum(num_arr,axis=0)
print(numpy.prod(sum_num_arr,axis=0))

# Min and Max

https://www.hackerrank.com/challenges/np-min-and-max/problem?isFullScreen=true

In [ ]:
import numpy
n,m = map(int,input().strip().split())

arr = []
for i in range(n):
    ip_arr = input().strip().split()
    arr.append(ip_arr)
    
num_arr = numpy.array(arr,int)

min_num_arr = numpy.min(num_arr,axis=1)
print(numpy.max(min_num_arr))

# Mean, Var, and Std***

https://www.hackerrank.com/challenges/np-mean-var-and-std/problem?isFullScreen=true

In [ ]:
import numpy

n,m = map(int,input().strip().split(' '))
arr = []
for i in range(n):
    ip_arr = input().strip().split()
    arr.append(ip_arr)
num_arr = numpy.array(arr,int)
print(numpy.mean(num_arr,axis=1))
print(numpy.var(num_arr,axis=0))
print(round(numpy.std(num_arr,axis=None),11))

# Dot and Cross***

https://www.hackerrank.com/challenges/np-dot-and-cross/problem?isFullScreen=true

In [ ]:
import numpy

n = int(input().strip())

arr_a = []
for i in range(n):
    ip_array_a = input().strip().split()
    arr_a.append(ip_array_a)

arr_b = []
for i in range(n):
    ip_array_b = input().strip().split()
    arr_b.append(ip_array_b)

num_arr_a = numpy.array(arr_a,int)
num_arr_b = numpy.array(arr_b,int)

print(numpy.dot(num_arr_a,num_arr_b))

# Inner and Outer

https://www.hackerrank.com/challenges/np-inner-and-outer/problem?isFullScreen=true

In [ ]:
import numpy

arr_a = numpy.array(input().strip().split(' '),int)
arr_b = numpy.array(input().strip().split(' '),int)

print(numpy.inner(arr_a,arr_b))
print(numpy.outer(arr_a,arr_b))

# Polynomials***

https://www.hackerrank.com/challenges/np-polynomials/problem?isFullScreen=true

In [ ]:
import numpy

coeff = list(map(float,input().strip().split()))
point = int(input().strip())

print(numpy.polyval(coeff,point))

# Linear Algebra***

https://www.hackerrank.com/challenges/np-linear-algebra/problem?isFullScreen=true

In [ ]:
import numpy

n =int(input().strip())
arr = []
for i in range(n):
    ip_arr = list(map(float,input().strip().split(' ')))
    arr.append(ip_arr)
    
#print(arr)

result = numpy.linalg.det(arr)
print(round(result,2))